# Generated by Django 5.1.6 on 2025-02-14 05:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_rename_location_hospital_category_and_more'),
        ('patients', '0003_alter_patientrecord_doctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='patient',
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('signs_and_symptoms', models.JSONField()),
                ('prescription', models.TextField()),
                ('diagnosed_disease', models.CharField(max_length=200)),
                ('medications', models.JSONField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
        migrations.DeleteModel(
            name='PatientRecord',
        ),
    ]
