# Generated by Django 5.1.6 on 2025-02-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_phone_number'),
        ('hospitals', '0002_remove_hospital_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='patients', to='hospitals.hospital'),
        ),
    ]
