# Generated by Django 5.1.6 on 2025-02-14 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_remove_hospital_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='location',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='email',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='user',
        ),
        migrations.AddField(
            model_name='hospital',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='image_url',
            field=models.URLField(default='https://www.google.com/imgres?q=migrating%20data%20from%20sqlite%20to%20postgres%20django&imgurl=https%3A%2F%2Fmedia2.dev.to%2Fdynamic%2Fimage%2Fwidth%3D1080%2Cheight%3D1080%2Cfit%3Dcover%2Cgravity%3Dauto%2Cformat%3Dauto%2Fhttps%253A%252F%252Fthepracticaldev.s3.amazonaws.com%252Fi%252Fc721xuxyf2anlbdazncj.png&imgrefurl=https%3A%2F%2Fdev.to%2Fthedevtimeline%2Fhow-to-migrate-data-from-sqlite-to-postgresql-in-django-182h&docid=rVlrvjE1AlD0gM&tbnid=6_mNKf-xUwDLYM&vet=12ahUKEwjsz4OossKLAxX0K_sDHePQG-YQM3oECEwQAA..i&w=1080&h=1080&hcb=2&ved=2ahUKEwjsz4OossKLAxX0K_sDHePQG-YQM3oECEwQAA'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('rating', models.FloatField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospital')),
            ],
        ),
    ]
